INSERT INTO diagnosis_rule (
    rule_code,
    name,
    status,
    rule_type,
    applicability,
    component_scope,
    signal_domain,
    metric_key,
    comparator,
    threshold_warn,
    threshold_alert,
    frequency_band_hint,
    pattern_text,
    recommendation,
    source_title,
    source_url,
    source_published_at,
    provenance,
    import_batch,
    notes,
    metadata
)
VALUES
(
    'RULE_KURTOSIS_WARN_GENERAL',
    'Kurtosis warning for bearing-fault screening',
    'ACTIVE',
    'THRESHOLD',
    'WIND_TURBINE_BEARING',
    'GENERIC_BEARING',
    'TIME_DOMAIN',
    'KURTOSIS',
    'GTE',
    4.0,
    NULL,
    NULL,
    'Treat kurtosis at or above 4 as a warning signal for bearing-fault investigation; healthy bearings are usually near 3.',
    'Escalate to envelope analysis and bearing-frequency review when kurtosis reaches the warning threshold.',
    'Test Investigation and Rule Analysis of Bearing Fault Diagnosis in Induction Motors',
    'https://www.mdpi.com/1996-1073/16/2/699',
    '2023',
    'WEB_PRIMARY',
    '2026-05-31-web-rule-seed-v1',
    'Warning threshold is source-backed; alert threshold remains in application defaults until a stronger source is curated.',
    '{"sourceKind":"research-paper","reviewStatus":"imported"}'::jsonb
),
(
    'RULE_ENVELOPE_LOCAL_DEFECT_GT_2KHZ',
    'Local defects should trigger envelope demodulation review',
    'ACTIVE',
    'PATTERN',
    'WIND_TURBINE_BEARING',
    'LOCAL_DEFECT',
    'ENVELOPE_SPECTRUM',
    'HIGH_FREQUENCY_RESONANCE',
    'GT',
    2000.0,
    NULL,
    '>2000 Hz',
    'Localized bearing defects excite high-frequency resonance bands above about 2 kHz; use envelope demodulation to expose the repetitive fault signature.',
    'Prefer envelope spectrum and characteristic-frequency matching before finalizing a localized-defect conclusion.',
    'Test Investigation and Rule Analysis of Bearing Fault Diagnosis in Induction Motors',
    'https://www.mdpi.com/1996-1073/16/2/699',
    '2023',
    'WEB_PRIMARY',
    '2026-05-31-web-rule-seed-v1',
    'This is stored as a pattern rule, not a direct alarm threshold.',
    '{"sourceKind":"research-paper","reviewStatus":"imported"}'::jsonb
),
(
    'RULE_CREST_FACTOR_IMPACTING',
    'Elevated crest factor indicates impacting',
    'ACTIVE',
    'PATTERN',
    'WIND_TURBINE_BEARING',
    'GENERIC_BEARING',
    'TIME_DOMAIN',
    'CREST_FACTOR',
    'TREND_UP',
    1.41,
    NULL,
    NULL,
    'Crest factor above the sine-wave baseline indicates impacting, and sustained growth is commonly associated with rolling-element wear.',
    'Trend crest factor over time and combine it with spectral evidence before escalating to a fault conclusion.',
    'What Is The “Crest Factor” And Why Is It Used?',
    'https://www.fluke.com/en-us/learn/blog/vibration/what-is-the-crest-factor-and-why-is-it-used',
    NULL,
    'WEB_PRIMARY',
    '2026-05-31-web-rule-seed-v1',
    'Threshold_warn records the physical baseline for non-impulsive sine waves, not a production alarm setpoint.',
    '{"sourceKind":"vendor-article","reviewStatus":"imported"}'::jsonb
),
(
    'RULE_BPFO_OUTER_RACE_HARMONICS',
    'BPFO harmonics indicate outer-race defects',
    'ACTIVE',
    'PATTERN',
    'WIND_TURBINE_BEARING',
    'OUTER_RACE',
    'FREQUENCY_DOMAIN',
    'BPFO_HARMONICS',
    'MULTIPLE_HARMONICS',
    NULL,
    NULL,
    '2-15x RPM',
    'Multiple harmonics around BPFO are a strong indicator of an outer-race defect.',
    'Check BPFO harmonics first, then confirm with envelope analysis when the raw spectrum is noisy.',
    'How to Interpret Condition Monitoring Data',
    'https://dewesoft.com/blog/how-to-interpret-condition-monitoring-data',
    NULL,
    'WEB_PRIMARY',
    '2026-05-31-web-rule-seed-v1',
    'Typical BPFO band is captured as a hint for review tooling, not a hard threshold.',
    '{"sourceKind":"vendor-article","reviewStatus":"imported"}'::jsonb
),
(
    'RULE_FTF_CAGE_HARMONICS',
    'FTF harmonics indicate cage defects',
    'ACTIVE',
    'PATTERN',
    'WIND_TURBINE_BEARING',
    'CAGE',
    'FREQUENCY_DOMAIN',
    'FTF_HARMONICS',
    'MULTIPLE_HARMONICS',
    NULL,
    NULL,
    '<0.5x RPM',
    'Multiple harmonics around FTF support a cage-defect diagnosis; the cage frequency usually stays below half running speed.',
    'Review cage-frequency harmonics before classifying a defect as raceway damage.',
    'How to Interpret Condition Monitoring Data',
    'https://dewesoft.com/blog/how-to-interpret-condition-monitoring-data',
    NULL,
    'WEB_PRIMARY',
    '2026-05-31-web-rule-seed-v1',
    'Stored as a pattern rule for future harmonic matching.',
    '{"sourceKind":"vendor-article","reviewStatus":"imported"}'::jsonb
),
(
    'RULE_BSF_ROLLING_ELEMENT_HARMONICS',
    'BSF harmonics indicate rolling-element defects',
    'ACTIVE',
    'PATTERN',
    'WIND_TURBINE_BEARING',
    'ROLLING_ELEMENT',
    'FREQUENCY_DOMAIN',
    'BSF_HARMONICS',
    'MULTIPLE_HARMONICS',
    NULL,
    NULL,
    '5-15x RPM',
    'Multiple harmonics around BSF support a rolling-element defect diagnosis.',
    'Use BSF harmonics with envelope results to separate rolling-element damage from generalized broadband wear.',
    'How to Interpret Condition Monitoring Data',
    'https://dewesoft.com/blog/how-to-interpret-condition-monitoring-data',
    NULL,
    'WEB_PRIMARY',
    '2026-05-31-web-rule-seed-v1',
    'Stored as a pattern rule for future harmonic matching.',
    '{"sourceKind":"vendor-article","reviewStatus":"imported"}'::jsonb
),
(
    'RULE_BPFI_INNER_RACE_HARMONICS',
    'BPFI harmonics indicate inner-race defects',
    'ACTIVE',
    'PATTERN',
    'WIND_TURBINE_BEARING',
    'INNER_RACE',
    'FREQUENCY_DOMAIN',
    'BPFI_HARMONICS',
    'MULTIPLE_HARMONICS',
    NULL,
    NULL,
    '4-15x RPM',
    'Multiple harmonics around BPFI support an inner-race defect diagnosis.',
    'When BPFI evidence is weak in the base spectrum, switch to envelope analysis before closing the diagnosis.',
    'How to Interpret Condition Monitoring Data',
    'https://dewesoft.com/blog/how-to-interpret-condition-monitoring-data',
    NULL,
    'WEB_PRIMARY',
    '2026-05-31-web-rule-seed-v1',
    'Stored as a pattern rule for future harmonic matching.',
    '{"sourceKind":"vendor-article","reviewStatus":"imported"}'::jsonb
),
(
    'RULE_LUBRICATION_HIGH_FREQUENCY_BAND',
    'High-frequency bands indicate lubrication issues',
    'ACTIVE',
    'PATTERN',
    'WIND_TURBINE_BEARING',
    'LUBRICATION',
    'FREQUENCY_DOMAIN',
    'HIGH_FREQUENCY_BAND',
    'BAND_PRESENT',
    NULL,
    NULL,
    '1000-20000 Hz',
    'High-frequency vibration concentrated in about 1 kHz to 20 kHz, especially in separated peak bands, is consistent with lubrication problems.',
    'Review lubrication state, temperature, and envelope results when this band pattern is present.',
    'How to Interpret Condition Monitoring Data',
    'https://dewesoft.com/blog/how-to-interpret-condition-monitoring-data',
    NULL,
    'WEB_PRIMARY',
    '2026-05-31-web-rule-seed-v1',
    'Mapped into a band hint because the source describes a frequency zone rather than a scalar threshold.',
    '{"sourceKind":"vendor-article","reviewStatus":"imported"}'::jsonb
),
(
    'RULE_LOOSENESS_RUNNING_SPEED_HARMONICS',
    '2x-4x harmonics support looseness diagnosis',
    'ACTIVE',
    'PATTERN',
    'WIND_TURBINE_BEARING',
    'LOOSENESS',
    'FREQUENCY_DOMAIN',
    'RUNNING_SPEED_HARMONICS',
    'MULTIPLE_HARMONICS',
    NULL,
    NULL,
    '2x-4x RPM',
    'Harmonic peaks at multiples of running speed, especially 2x to 4x, support a mechanical-looseness diagnosis.',
    'Cross-check the spectrum with waveform impacts and unstable phase before closing as looseness.',
    'Mechanical looseness: what it is and how to detect it',
    'https://www.fluke.com/ja-jp/learn/blog/predictive-maintenance/mechanical-looseness-what-it-is-how-to-detect',
    NULL,
    'WEB_PRIMARY',
    '2026-05-31-web-rule-seed-v1',
    'Source uses harmonics plus unstable phase and impacts as a combined indicator.',
    '{"sourceKind":"vendor-article","reviewStatus":"imported"}'::jsonb
),
(
    'RULE_SHAFT_BEARING_LOOSENESS_3X',
    '3x RPM peak hints at bearing-to-shaft looseness',
    'ACTIVE',
    'PATTERN',
    'WIND_TURBINE_BEARING',
    'LOOSENESS',
    'FREQUENCY_DOMAIN',
    'SHAFT_LOOSENESS_3X',
    'DOMINANT_PEAK',
    3.0,
    NULL,
    '3x RPM',
    'A dominant 3x RPM harmonic is a focused hint of looseness between the bearing and the shaft.',
    'Inspect fits, fretting, and mounting integrity when a 3x RPM harmonic becomes dominant.',
    'How to Interpret Condition Monitoring Data',
    'https://dewesoft.com/blog/how-to-interpret-condition-monitoring-data',
    NULL,
    'WEB_PRIMARY',
    '2026-05-31-web-rule-seed-v1',
    'Kept as a review hint for future rule-engine use.',
    '{"sourceKind":"vendor-article","reviewStatus":"imported"}'::jsonb
),
(
    'RULE_BEARING_MISALIGNMENT_NBXRPM',
    'Rolling-element-count harmonics suggest misalignment',
    'ACTIVE',
    'PATTERN',
    'WIND_TURBINE_BEARING',
    'MISALIGNMENT',
    'FREQUENCY_DOMAIN',
    'NB_TIMES_RPM',
    'DOMINANT_PEAK',
    NULL,
    NULL,
    'NB x RPM',
    'Running-speed harmonics with a strong component near the rolling-element count times RPM suggest bearing misalignment.',
    'Review coupling alignment and shaft geometry before classifying the signal as a pure bearing fault.',
    'How to Interpret Condition Monitoring Data',
    'https://dewesoft.com/blog/how-to-interpret-condition-monitoring-data',
    NULL,
    'WEB_PRIMARY',
    '2026-05-31-web-rule-seed-v1',
    'Useful as a catalog rule until order-tracking and richer kinematic matching are added.',
    '{"sourceKind":"vendor-article","reviewStatus":"imported"}'::jsonb
)
ON CONFLICT (rule_code) DO UPDATE
SET name = EXCLUDED.name,
    status = EXCLUDED.status,
    rule_type = EXCLUDED.rule_type,
    applicability = EXCLUDED.applicability,
    component_scope = EXCLUDED.component_scope,
    signal_domain = EXCLUDED.signal_domain,
    metric_key = EXCLUDED.metric_key,
    comparator = EXCLUDED.comparator,
    threshold_warn = EXCLUDED.threshold_warn,
    threshold_alert = EXCLUDED.threshold_alert,
    frequency_band_hint = EXCLUDED.frequency_band_hint,
    pattern_text = EXCLUDED.pattern_text,
    recommendation = EXCLUDED.recommendation,
    source_title = EXCLUDED.source_title,
    source_url = EXCLUDED.source_url,
    source_published_at = EXCLUDED.source_published_at,
    provenance = EXCLUDED.provenance,
    import_batch = EXCLUDED.import_batch,
    notes = EXCLUDED.notes,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();
